language: java
jdk:
  - oraclejdk8

before_install:
  - mkdir -p $HOME/gopath/src/sourcegraph.com/sourcegraph
  - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/sourcegraph.com/sourcegraph/srclib-basic
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/sourcegraph.com/sourcegraph/srclib-basic
  - mkdir -p $HOME/.srclib/sourcegraph.com/sourcegraph/

install:
# installing srclib
  - export GOPATH=$HOME/gopath
  - go get -u -v sourcegraph.com/sourcegraph/srclib/cmd/srclib
  - export PATH=$PATH:$HOME/gopath/bin
# installing toolchain
  - ln -s $TRAVIS_BUILD_DIR $HOME/.srclib/sourcegraph.com/sourcegraph/srclib-basic
  - make install

script:
  - srclib test 
